name: Generate Gerber files

on:
  push:
    paths:
    - '**.kicad_pcb'
    - '**.kibot.yml'
  pull_request:
    paths:
    - '**.kicad_pcb'
    - '**.kibot.yml'
  workflow_dispatch:
    inputs:
      name:
        description: 'Workflow run name'
        required: false
        default: 'Manual test run'
  
jobs:   
  pcb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.3.1
      with:
        config: gerber.kibot.yml
        dir: gerber
        schema: 'pcb/*.sch'
        board: 'pcb/*.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: gerber
        path: gerber
